### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by agyrafa** [arkon/ng-inline-svg#11]
When I enter npm install on the demo directory, I get this error 
npm ERR! ng2-inline-svg@1.2.0 lint: `tslint src/**/*.ts`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ng2-inline-svg@1.2.0 lint script 'tslint src/**/*.ts'.
npm ERR! This is most likely a problem with the ng2-inline-svg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint src/**/*.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-inline-svg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ng2-inline-svg
npm ERR! There is likely additional logging output above.

**Comment by agyrafa** [comment]
actually, with sudo it worked... but now, when I enter npm start, I get this error

ERROR in ./src/bootstrap.ts
(4,33): error TS2307: Cannot find module 'ng2-inline-svg'.

ERROR in ./src/bootstrap.ts
Module not found: Error: Cannot resolve module 'ng2-inline-svg' in /Users/agyrafa/Desktop/ng2-inline-svg-master/demo/src
 @ ./src/bootstrap.ts 14:23-48
webpack: bundle is now VALID.

**Comment by arkon** [comment]
@agyrafa Is there an actual linting error that shows up? It seems to lint/build properly on my end.

**Comment by agyrafa** [comment]
ERROR in ./~/ng2-inline-svg/src/index.ts
Module parse failed: /Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/ng2-inline-svg/src/index.ts Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (6:0)
    at Parser.pp$4.raise (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.pp$7.next (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2413:10)
    at Parser.pp.eat (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:536:12)
    at Parser.pp.semicolon (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:15)
    at Parser.pp$1.parseImport (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1243:10)
    at Parser.pp$1.parseStatement (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:719:46)
    at Parser.pp$1.parseTopLevel (/Users/agyrafa/Desktop/ng2-inline-svg-master/demo/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
 @ ./src/bootstrap.ts 14:9-55
webpack: bundle is now VALID.

**Comment by arkon** [comment]
What version of Typescript do you have installed?

**Comment by agyrafa** [comment]
typescript@2.0.7 node_modules/typescript

**Comment by arkon** [comment]
Eh, I can't think of why it'd be failing. I can only suggest pulling down a fresh copy and trying to install the Node dependencies again?

EDIT: also make sure you build the main project before the demo.

**Comment by agyrafa** [comment]
i did the steps again and it worked :) thanks
