### ISSUE TITLE
ERROR DOMException: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by hrishikeshpotdar91** [arkon/ng-inline-svg#85]
Hi, 

I keep getting this error in my console, 
I'm not sure how to fix this 

core.js:1449 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at InlineSVGDirective._evalScripts (webpack-internal:///./node_modules/ng-inline-svg/lib/inline-svg.directive.js:136:21)
    at SafeSubscriber.eval [as _next] (webpack-internal:///./node_modules/ng-inline-svg/lib/inline-svg.directive.js:83:23)
    at SafeSubscriber.__tryOrUnsub (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:248:16)
    at SafeSubscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:195:22)
    at Subscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:136:26)
    at Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:100:18)
    at MapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/map.js:88:26)
    at MapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:100:18)
    at RefCountSubscriber.Subscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:136:26)
    at RefCountSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:100:18)

using this version 

 "ng-inline-svg": "8.0.0"

**Comment by arkon** [comment]
What's the SVG code and what browser?
